import 'package:get/get_navigation/src/root/internacionalization.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        // English language
        'en_US': {
          'Kidscoin': 'kidscoin',
          'Prohibited products': 'Prohibited products',
          'Edit Profile': 'Edit Profile',
          'changePassword': 'Change Password',
          'cakes': 'cakes',
          'notification': 'Notification',
          'None': 'None',
          'Soda': 'Soda',
          'Username': 'UserName',
          'Your full name...': 'Your full name...',
          'Password': 'Password',
          'PhoneNumber': 'PhoneNumber',
          'Confirm Password': 'Confirm Password',
          'Check again': 'Check again',
          'please select an image': 'please select an image',
          'new child added': 'new child added',
          'you added a new child named': 'you added a new child named',
          'outfit': 'outfit',
          'Add Product': 'Add Product',
          'Product Name': 'Product Name',
          'Product Name is required': 'Product Name is required',
          'Description': 'Description',
          'Description is required': 'Description is required',
          'Price': 'Price',
          'Price is required': 'Price is required',
          'Type': 'Type',
          'Type is required': 'Type is required',
          'Remove Image': 'Remove Image',
          'Change Image': 'Change Image',
          'Select Image': 'Select Image',
          'Success': 'Success',
          'save': 'save',
          'Product added successfully.': 'Product added successfully.',
          'Gallery': 'Gallery',
          'Cancel': 'Cancel',
          'Add Video': 'Add Video',
          'Reel Description': 'Reel Description',
          'Music Name': 'Music Name',
          'Pick Video': 'Pick Video',
          'Confirm': 'Confirm',
          'Edit Profile': 'Edit Profile',
          'Username': 'Username',
          'Please enter your user name': 'Please enter your user name',
          'Phone number': 'Phone number',
          'Enter your mobile number': 'Enter your mobile number',
          'Email': 'Email',
          'Enter your email': 'Enter your email',
          'Get your secret key back': 'Get your secret key back',
          'language': 'language',
          'update': 'update',
          'Logout': 'Logout',
          'Profile updated successfully': 'Profile updated successfully',
          'Your Childrens': 'Your Childrens',
          'recharge your childs account ': 'recharge your childs account ',
          'Submit': 'Submit',
          'add a new child to the family ': 'add a new child to the family ',
          'Edit Product': 'Edit Product',
          'Would you like to update your generated password to remember it easier?':
              'Would you like to update your generated password to remember it easier?',
          'No': 'No',
          'Yes': 'Yes',
          'Update Your Password': 'Update Your Password',
          'New Password': 'New Password',
          'Confirm New Password': 'Confirm New Password',
          'Please fill in both fields': 'Please fill in both fields',
          'My Products': 'My Products',
          'Buy a Product': 'Buy a Product',
          'Add a Product to Sell': 'Add a Product to Sell',
          'Are you sure you want to delete this product?':
              'Are you sure you want to delete this product?',
          'Delete': 'Delete',
          'Notifications': 'Notifications',
          'Congratulations': 'Congratulations',
          'You won the game!': 'You won the game!',
          'Game Over': 'Game Over',
          'You lost the game!': 'You lost the game!',
          'Spam': 'Spam',
          'Hate Speech': 'Hate Speech',
          'Violence': 'Violence',
          'Nudity': 'Nudity',
          'Copyright Infringement': 'Copyright Infringement',
          'Other': 'Other',
          'Home': 'Home',
          'Market': 'Market',
          'Reels': 'Reels',
          'tasks': 'tasks',
          'Profile': 'Profile'
        },
// French language
        'fr_FR': {
          'Kidscoin': 'kidscoin',
          'Prohibited products': 'Produits interdits',
          'Edit Profile': 'Modifier le profil',
          'changePassword': 'Changer le mot de passe',
          'cakes': 'cakes',
          'notification': 'Notification',
          'None': 'Aucun',
          'Soda': 'Soda',
          'Username': 'Nom d\'utilisateur',
          'Your full name...': 'Votre nom complet...',
          'Password': 'Mot de passe',
          'PhoneNumber': 'Numéro de téléphone',
          'Confirm Password': 'Confirmer le mot de passe',
          'Check again': 'Vérifier à nouveau',
          'please select an image': 'Veuillez sélectionner une image',
          'new child added': 'Nouvel enfant ajouté',
          'you added a new child named':
              'Vous avez ajouté un nouvel enfant nommé',
          'outfit': 'outfit',
          'Add Product': 'Ajouter un produit',
          'Product Name': 'Nom du produit',
          'Product Name is required': 'Le nom du produit est requis',
          'Description': 'Description',
          'Description is required': 'La description est requise',
          'Price': 'Prix',
          'Price is required': 'Le prix est requis',
          'Type': 'Type',
          'Type is required': 'Le type est requis',
          'Remove Image': 'Supprimer l\'image',
          'Change Image': 'Changer l\'image',
          'Select Image': 'Sélectionner une image',
          'Success': 'Succès',
          'save': 'Enregistrer',
          'Product added successfully.': 'Produit ajouté avec succès.',
          'Gallery': 'Galerie',
          'Cancel': 'Annuler',
          'Add Video': 'Ajouter une vidéo',
          'Reel Description': 'Description de la bobine',
          'Music Name': 'Nom de la musique',
          'Pick Video': 'Choisir une vidéo',
          'Confirm': 'Confirmer',
          'Edit Profile': 'Modifier le profil',
          'Username': 'Nom d\'utilisateur',
          'Please enter your user name':
              'Veuillez saisir votre nom d\'utilisateur',
          'Phone number': 'Numéro de téléphone',
          'Enter your mobile number': 'Entrez votre numéro de portable',
          'Email': 'E-mail',
          'Enter your email': 'Entrez votre e-mail',
          'Get your secret key back': 'Récupérez votre clé secrète',
          'language': 'Langue',
          'update': 'Mettre à jour',
          'Logout': 'Déconnexion',
          'Profile updated successfully': 'Profil mis à jour avec succès',
          'Your Childrens': 'Vos enfants',
          'recharge your childs account ':
              'Rechargez le compte de votre enfant',
          'Submit': 'Soumettre',
          'add a new child to the family ':
              'Ajouter un nouvel enfant à la famille',
          'Edit Product': 'Modifier le produit',
          'Would you like to update your generated password to remember it easier?':
              'Souhaitez-vous mettre à jour votre mot de passe généré pour le mémoriser plus facilement ?',
          'No': 'Non',
          'Yes': 'Oui',
          'Update Your Password': 'Mettre à jour votre mot de passe',
          'New Password': 'Nouveau mot de passe',
          'Confirm New Password': 'Confirmer le nouveau mot de passe',
          'Please fill in both fields': 'Veuillez remplir les deux champs',
          'My Products': 'Mes produits',
          'Buy a Product': 'Acheter un produit',
          'Add a Product to Sell': 'Ajouter un produit à vendre',
          'Are you sure you want to delete this product?':
              'Êtes-vous sûr de vouloir supprimer ce produit ?',
          'Delete': 'Supprimer',
          'Notifications': 'Notifications',
          'Congratulations': 'Félicitations',
          'You won the game!': 'Vous avez gagné le jeu !',
          'Game Over': 'Fin du jeu',
          'You lost the game!': 'Vous avez perdu le jeu !',
          'Spam': 'Spam',
          'Hate Speech': 'Discours de haine',
          'Violence': 'Violence',
          'Nudity': 'Nudité',
          'Copyright Infringement': 'Violation du droit d\'auteur',
          'Other': 'Autre',
          'Home': 'Accueil',
          'Market': 'Marché',
          'Reels': 'Bobines',
          'tasks': 'tâches',
          'Profile': 'Profil',
          'All': 'Tous',
          'Ongoing': 'En cours',
          'Completed': 'Terminé',
          'No tasks found': 'Aucune tâche trouvée',
          'Tasks': 'Tâches'
        },

// Arabic language
        'ar_AR': {
          'Kidscoin': 'عملة الأطفال',
          'Prohibited products': 'المنتجات الممنوعة',
          'Edit Profile': 'تحرير الملف الشخصي',
          'changePassword': 'تغيير كلمة المرور',
          'cakes': 'كعك',
          'notification': 'الإشعار',
          'None': 'لا شيء',
          'Soda': 'صودا',
          'Username': 'اسم المستخدم',
          'Your full name...': 'اسمك الكامل...',
          'Password': 'كلمة المرور',
          'PhoneNumber': 'رقم الهاتف',
          'Confirm Password': 'تأكيد كلمة المرور',
          'Check again': 'تحقق مرة أخرى',
          'please select an image': 'الرجاء تحديد صورة',
          'new child added': 'تمت إضافة طفل جديد',
          'you added a new child named': 'لقد أضفت طفلاً جديداً يدعى',
          'outfit': 'زي',
          'Add Product': 'إضافة منتج',
          'Product Name': 'اسم المنتج',
          'Product Name is required': 'اسم المنتج مطلوب',
          'Description': 'الوصف',
          'Description is required': 'الوصف مطلوب',
          'Price': 'السعر',
          'Price is required': 'السعر مطلوب',
          'Type': 'النوع',
          'Type is required': 'النوع مطلوب',
          'Remove Image': 'إزالة الصورة',
          'Change Image': 'تغيير الصورة',
          'Select Image': 'اختر صورة',
          'Success': 'نجاح',
          'save': 'حفظ',
          'Product added successfully.': 'تمت إضافة المنتج بنجاح.',
          'Gallery': 'المعرض',
          'Cancel': 'إلغاء',
          'Add Video': 'إضافة فيديو',
          'Reel Description': 'وصف البكرة',
          'Music Name': 'اسم الموسيقى',
          'Pick Video': 'اختر فيديو',
          'Confirm': 'تأكيد',
          'Edit Profile': 'تعديل الملف الشخصي',
          'Username': 'اسم المستخدم',
          'Please enter your user name': 'الرجاء إدخال اسم المستخدم الخاص بك',
          'Phone number': 'رقم الهاتف',
          'Enter your mobile number': 'أدخل رقم هاتفك المحمول',
          'Email': 'البريد الإلكتروني',
          'Enter your email': 'أدخل بريدك الإلكتروني',
          'Get your secret key back': 'استعادة مفتاحك السري',
          'language': 'لغة',
          'update': 'تحديث',
          'Logout': 'تسجيل الخروج',
          'Profile updated successfully': 'تم تحديث الملف الشخصي بنجاح',
          'Your Childrens': 'أطفالك',
          'recharge your childs account ': 'إعادة شحن حساب طفلك',
          'Submit': 'إرسال',
          'add a new child to the family ': 'إضافة طفل جديد إلى العائلة',
          'Edit Product': 'تحرير المنتج',
          'Would you like to update your generated password to remember it easier?':
              'هل ترغب في تحديث كلمة المرور التي تم إنشاؤها لتذكرها بسهولة؟',
          'No': 'لا',
          'Yes': 'نعم',
          'Update Your Password': 'تحديث كلمة المرور الخاصة بك',
          'New Password': 'كلمة السر الجديدة',
          'Confirm New Password': 'تأكيد كلمة المرور الجديدة',
          'Please fill in both fields': 'يرجى ملء الحقلين',
          'My Products': 'منتجاتي',
          'Buy a Product': 'شراء منتج',
          'Add a Product to Sell': 'إضافة منتج للبيع',
          'Are you sure you want to delete this product?':
              'هل أنت متأكد أنك تريد حذف هذا المنتج؟',
          'Delete': 'حذف',
          'Notifications': 'الإشعارات',
          'Congratulations': 'تهانينا',
          'You won the game!': 'لقد فزت باللعبة!',
          'Game Over': 'نهاية اللعبة',
          'You lost the game!': 'لقد خسرت اللعبة!',
          'Spam': 'رسائل غير مرغوب فيها',
          'Hate Speech': 'خطاب الكراهية',
          'Violence': 'عنف',
          'Nudity': 'عري',
          'Copyright Infringement': 'انتهاك حقوق الطبع والنشر',
          'Other': 'آخر',
          'Home': 'الصفحة الرئيسية',
          'Market': 'السوق',
          'Reels': 'البكرات',
          'tasks': 'المهام',
          'Profile': 'الملف الشخصي',
          'All': 'الكل',
          'Ongoing': 'قيد التقدم',
          'Completed': 'مكتمل',
          'No tasks found': 'لم يتم العثور على مهام',
          'Tasks': 'المهام',
          'Quiz with AI': 'اختبار مع الذكاء الاصطناعي',
        },
      };
}
