// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD5qQebYtaPYoui_CJIQYVs7p1BGWF980',
    appId: '1:27810660519:web:9bde4a68ad41f5c7fb5b82',
    messagingSenderId: '27810660519',
    projectId: 'pim2024-63da1',
    authDomain: 'pim2024-63da1.firebaseapp.com',
    storageBucket: 'pim2024-63da1.appspot.com',
    measurementId: 'G-7N3G47DB4K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl5z8HeELOcNDGNfR4SOPLWsru4T0VYGM',
    appId: '1:27810660519:android:cf9e9b67def7871efb5b82',
    messagingSenderId: '27810660519',
    projectId: 'pim2024-63da1',
    storageBucket: 'pim2024-63da1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyyBd2ENs9Y-zdSE7I_vEVDfuF0H9VZM8',
    appId: '1:27810660519:ios:83621142b93f7782fb5b82',
    messagingSenderId: '27810660519',
    projectId: 'pim2024-63da1',
    storageBucket: 'pim2024-63da1.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyyBd2ENs9Y-zdSE7I_vEVDfuF0H9VZM8',
    appId: '1:27810660519:ios:83621142b93f7782fb5b82',
    messagingSenderId: '27810660519',
    projectId: 'pim2024-63da1',
    storageBucket: 'pim2024-63da1.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCD5qQebYtaPYoui_CJIQYVs7p1BGWF980',
    appId: '1:27810660519:web:d3930f6d6a78f6e3fb5b82',
    messagingSenderId: '27810660519',
    projectId: 'pim2024-63da1',
    authDomain: 'pim2024-63da1.firebaseapp.com',
    storageBucket: 'pim2024-63da1.appspot.com',
    measurementId: 'G-FFT8QPXDFH',
  );

}